# Generated by Django 3.0.2 on 2020-02-19 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhataApp', '0002_auto_20200218_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('product_insert_date', models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 19, 22, 357911))),
            ],
        ),
    ]
