# Generated by Django 3.0.3 on 2020-03-04 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhataApp', '0004_auto_20200219_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_insert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 11, 5, 11, 927904)),
        ),
    ]
